---
engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.scss"
exclude_paths:
  - node_modules/**/*
  - coverage/**/*
  - dist/**/*
  - documentation/**/*

